<?php
    header('Content-Type: text/xml; charset="UTF-8"');
?>
<notes>
    <note>
            <title>Note1</title>
            <authors>
                <name>123</name>
                <name>2456</name>
            </authors>
            <price>300</price>
    </note>
    <note>
            <title>Note2</title>
            <authors>
                  <name>111</name>
                  <name>222</name>
                  <name>3333</name>
            </authors>
            <price>1500</price>
    </note>
</notes>